DATA:
  root_dataset: "./data/"
  list_train: "./data/outside15k_train.odgt"
  list_val: "./data/example_image_list.odgt"
  list_stats: "./data/outside15k_val.odgt"
  num_class: 24
  img_sizes: (300, 400, 500, 600, 700, 800)
  img_max_size: 1100
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True
  random_crop: True
  class_info: "./data/outside15k.json"
  
MODEL:
  arch_encoder: "resnet50"
  arch_decoder: "outsideNet"
  fc_dim: 2048
  spatial_mask: True

TRAIN:
  batch_size_per_gpu: 2
  start_epoch: 35
  num_epoch: 100
  epoch_iters: 10000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 1
  disp_iter: 50
  eval: False

EVAL:
  checkpoint: "epoch_50.pth"
  visualize: True
  multi_scale: False

TEST:
  checkpoint: "epoch_50.pth"
  result: "./test_output/"
  multi_scale: False

DIR: "weights/"
